name: Build macOS .app for Salary Calculator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos-app:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas matplotlib openpyxl

    - name: Build macOS GUI App
      run: |
        pyinstaller salary_calculator_v28.py --onefile --windowed --name SalaryApp
        ls -lh dist/

    - name: Upload .app artifact
      uses: actions/upload-artifact@v4
      with:
        name: SalaryApp-macOS
        path: dist/SalaryApp.app
